include:
  - template: Terraform.latest.gitlab-ci.yml

variables:
  TF_STATE_NAME: terraform
  TF_CACHE_KEY: terraform
  TF_ROOT: ${CI_PROJECT_DIR}/tf

deploy_site:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 sync ./ s3://$S3_BUCKET_NAME --delete --exclude '.git/*' --exclude '.gitlab-ci.yml' --exclude 'tf/*'
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  only:
    - main
