title: JosephGruber.com
description: 'Joseph Gruber is a engineering manager leading teams building software and systems for NASA spacecraft, landscape photography and astrophotography enthusiast, space geek, coffee aficionado, private pilot, and future Mars resident.'
headline: 'Thoughts from a spacecraft engineering manager, photographer, coffee aficionado, and future Mars resident.'

url: 'https://josephgruber.com'
baseurl: ''
asseturl: '/assets'


google_analytics: 'UA-12826609-1'

author:
  name: 'Joseph Gruber'
  email: joseph.gruber@gmail.com
  twitter_username: josephgruber
  facebook_username: joseph.gruber
  instagram_username: josephgruber
  linkedin_username:  josephgruber

facebook:
  publisher: 1065184637
  admins: 1065184637

social:
  links:
    - https://twitter.com/josephgruber
    - https://www.facebook.com/joseph.gruber
    - https://www.linkedin.com/in/josephgruber
    - https://www.instagram.com/josephgruber/
    - https://keybase.io/josephgruber
    - https://gitlab.com/joseph.gruber

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
future: false

kramdown:
  input: GFM

plugins: ['jekyll-paginate', 'jekyll-sitemap']
exclude: ['Gemfile', 'Gemfile.lock', '.DS_Store', 's3_website.yml', 'template.md', 'package.json', 'package-lock.json', 'node_modules', 'gulpfile.js']
